baseURL = ""
relativeURLs = true
title = "Survey Solutions"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

defaultContentLanguageInSubdir = "true"
DefaultContentLanguage = "en"

[languages]
    [languages.en]
    LanguageName = "English"

    [languages.ru]
    LanguageName = "Русский"

    [languages.es]
    LanguageName = "Español"

    [languages.fr]
    LanguageName =  "Français"

    [languages.ar]
    LanguageName = "العربية"

    [languages.pt]
    LanguageName = "Português"

    [languages.zh]
    LanguageName = "中文"


[params]
LatestVersion = "22.09"
demoArticleLink = "https://docs.mysurvey.solutions/headquarters/config/demo-server/"
